title = "CLIQ"
baseURL = "https://cliqteam.com/"
languageCode = "en-us"
theme = "beautifulhugo"

[Params]
subtitle = "Follow our Tech Journey"
#   logo = "img/avatar-icon.png" # Expecting square dimensions
#   favicon = "img/favicon.ico"
date_format = "%Y-%m-%d %H:%M"

[Author]
name = "CLIQ"
website = "https://cliqteam.com/"
# email = "cliq@gmail.com"
github = "cliqteam"
