title = "Cliq"
baseURL = "https://cliqteam.github.io/blog/"
languageCode = "en-us"
theme = "beautifulhugo"

[Params]
subtitle = "Building beautiful and simple applications"
#   logo = "img/avatar-icon.png" # Expecting square dimensions
#   favicon = "img/favicon.ico"
dateFormat = "January 2, 2006"
