title = "Cliq Blog"
baseURL = "https://cliqteam.github.io/blog/"
languageCode = "en-us"
theme = "beautifulhugo"

[Params]
subtitle = "Follow our Tech Journey"
#   logo = "img/avatar-icon.png" # Expecting square dimensions
#   favicon = "img/favicon.ico"
date_format = "%Y-%m-%d %H:%M"
